### ISSUE TITLE
Support resolving assemblies from multi-file packages

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter.ApplicationAssemblyLoader#1]
Found the initial strategy to resolve dependencies is to trivial in terms of that it will fail to resolve dependencies to files in multi-assembly package. So currently it fails resolving our `Starcounter.QueryProcessor` package, whose content look like this:

![image](https://user-images.githubusercontent.com/2902045/39111983-5b51c54e-46d7-11e8-898f-dade3073eb1c.png)

Need to investigate some on how such packages actually are meant to resolve.

**Comment by per-samuelsson** [comment]
BTW, @bigwad, is it by design `Starcounter.QueryProcessor` package contain all that?

**Comment by bigwad** [comment]
Yes, because I wanted it to be modular and modularity emerged kind of naturally because most of the assemblies here were separate assemblies in 2.3 also. But as there were no clients for them besides QueryProcessor, I packed them into the single package to not overcomplicate packaging.
Didn't think it's so uncommon to have a mutli-assembly package

**Comment by per-samuelsson** [comment]
> Didn't think it's so uncommon to have a mutli-assembly package

I've seen it used from time to time in tooling, when you package like an exe and some dependencies in one package for distribution. But other than that, I find only one package in my cache designed like that: `Starcounter.QueryProcessor`.

WTBS, that's no proof it's uncommon obv.

But anyway, I implemented a simple algorithm that worked, just comparing files in the package against the name of it, and picking a single one (or null if no matches, or more match than one), and that got me passed that. But then next problem arose, there was a Load for `Starcounter.PrologFacade`, because that could not resolve at all, because it's hidden in that package. Then our shared host resolver failed. Guess I need to find a way to support that as well, but not exactly sure how though.

**Comment by per-samuelsson** [comment]
Tried to come up with other alternatives yesterday, but can't find any better than the below, so I'll probably implement that one if no one object.

> I redesign resolving and maintain a cache over all assemblies previously loaded by our custom resolver for a given context. When the standard custom resolve fail (like it does for those assemblies hiding in the QP-multi-package), I scan through all loaded assemblies and see if I can find a single one next to one of those. Then I load that.

**Comment by per-samuelsson** [comment]
I now have an implementation for the above, and that get's us around resolving all active references in Nova sample app (including those hidden in `Starcounter.QueryProcessor`. 

It's based on that if there's a dependency that is not listed as a dependency by the build system, and it's still needed to run the application, we probe all locations of already loaded assemblies for a (single-only) reference, and if we find it, we load it.

However, we might need to refine that further if we need to load the entire dependency tree upfront (which we currently need to do, b/c how binding work in Nova). The reason is we can't control the order there, so might be so that a dependency is loaded *before* any other dependency actually need it, and that will beat the current design I think.

**Comment by per-samuelsson** [comment]
> However, we might need to refine that further if we need to load the entire dependency tree upfront (which we currently need to do, b/c how binding work in Nova). The reason is we can't control the order there, so might be so that a dependency is loaded before any other dependency actually need it, and that will beat the current design I think.

Managed to redesign the forceful dependency loader so that we cover that case also.

**Comment by per-samuelsson** [comment]
Okay, so this is now done, and part of new published package `https://www.myget.org/feed/starcounter/package/nuget/Starcounter.ApplicationAssemblyLoader`, version `0.1.0-alpha-000076`.
